### ISSUE TITLE
Reach

### ISSUE THREAD

**Issue by N3ROO** [N3ROO/Bettercolors#52]
If forge prevents it, then find a work around by injecting code or modifying packets (dangerous)

**Comment by SorosBoy** [comment]
Maybe you know you can move the hitbox

**Comment by N3ROO** [comment]
Reach is working on the development branch (see commit 995e5a8765a583914f6d165ae230b04eec6783ca)

The idea is to replace the minecraft's PlayerControllerMP class to our own PlayerControllerMC, so that we can update anything just by using @override.

I will release the new version (7.0.0) soon, maybe tomorrow if I'm good enough. I need to update some parts of the engine:
- Layout
- Better error handling for modules' instantiation
- Add a getInstance method to use utility functions

Once that the engine will be released, I will need to integrate the new friends system in the Bettercolors mod. 

I expect to release the 7.0.0 version tomorrow or friday on Minecraft 1.8.9. The release for Minecraft 1.16.1 should come shortly after.

**Comment by N3ROO** [comment]
added in 7.0.0
