### ISSUE TITLE
add a triggerbot?

### ISSUE THREAD

**Issue by OverheadOcean** [N3ROO/Bettercolors#58]
auto clicks when looking at entity

**Comment by N3ROO** [comment]
Why not, it won't be hard to implement a triggerbot. The thing is that some servers with custom anti-cheats spawn entities around you when fighting (i.e. Hypixel). It's not a super-safe feature, but it sounds good. When I will have some time, will analyze those entities to make sure that the triggerbot ignores them.

Thank you for your suggestion!

**Comment by OverheadOcean** [comment]
> Why not, it won't be hard to implement a triggerbot. The thing is that some servers with custom anti-cheats spawn entities around you when fighting (i.e. Hypixel). It's not a super-safe feature, but it sounds good. When I will have some time, will analyze those entities to make sure that the triggerbot ignores them.
> 
> Thank you for your suggestion!

also try using mouse clicks instead of packets as it'll be harder to detect

**Comment by N3ROO** [comment]
> also try using mouse clicks instead of packets as it'll be harder to detect

Yeah, that's how the mouse assistance currently works by default (you can switch to packets by turning on the "packets" option). I prefer using raw mouse click because that's way more safe, so no worries about that :)
