### ISSUE TITLE
Sticky aim

### ISSUE THREAD

**Issue by wieisstimpee** [N3ROO/Bettercolors#65]
Hello, I think I have found a solution for the aimassist not looking that legit, what if there was a option for sticky aim? The aimassist doesnt work until your crossair is actually on the player then the aimassist starts working and tries to stay on the player.
I hope I described it well enough, you dont have to add this feature but it would be cool if you did.

**Comment by N3ROO** [comment]
Hey! It's a great idea, and it's definitely doable. I will implement that for 7.3.0. The engine is ready, so most of the work is already done

**Comment by wieisstimpee** [comment]
Alright great!

**Comment by N3ROO** [comment]
Done for MC1.16.2 (forge) https://github.com/N3ROO/Bettercolors/releases/tag/7.3.0-MC1.16.2
