### ISSUE TITLE
Anti bot for Hypixel

### ISSUE THREAD

**Issue by wieisstimpee** [N3ROO/Bettercolors#66]
I am not sure how hard it is to make one, but there are other cheats out there that simply filter based on how many ticks the player was alive. E.g if alive for longer than 40 ticks it attacks the player, or if the player is "derping" (spinning around hitting and such) or based on entity ID. I am willing to provide more info on what to filter if needed.

**Comment by N3ROO** [comment]
Hey! Thanks for your request. So if I understand correctly, the goal of an antibot is to prevent attacking bots? If that's the case, there are a lot of filter than we can use:

It is a bot if the entity:
- Lived less than x ticks
- Name color is white
- Attacks something
- Health is greater than 20
- ID is less than 0 or greater than a high number
- Rotation are greater than 90 or less than -90
- Is invisible
- Has no armor
- Ping is 0
- Was not hit yet
- Is not in the tab window (the window where the players are listed)
- Is duplicated in the world

Every one of these filters should be customizable. Which is a lot of work, but it will be useful! The first step here would be to go to Hypixel, to analyze and understand the behavior of these bots (their ID, name tags, where do they spawn and so on)

**Comment by wieisstimpee** [comment]
Hey, I know a lot about the behavior of the bots, years of experience in fact 
* Dont attack if it lived shorter than 40 ticks.
* Name is red (enemy players name are red too so we cant filter that)
* They always attack you
* Health is random
* ID is random, they have moving characters
* They rotate randomly (360 degrees)
* They are visible
* They sometimes have armor
* Ping i dont know
* Was not hit yet
* We could filter on is not in tab window
* We could also filter on duplicated in the world

There is a open source mod that has anti bot ill link it: https://github.com/CCBlueX/LiquidBounce

**Comment by N3ROO** [comment]
Done for MC1.16.2 (forge) https://github.com/N3ROO/Bettercolors/releases/tag/7.3.0-MC1.16.2
