### ISSUE TITLE
1.16.4 support.

### ISSUE THREAD

**Issue by GithubThrowaway69** [N3ROO/Bettercolors#80]
Is support for 1.16.4 planned?

I can't find any minecraft mods with the basic features this one has that offer support for 1.16.4. I even own a paid client that still has not updated past 1.12.2. It would be really nice if I could have access to the simple features this mod this offers for 1.16.4.

**Comment by N3ROO** [comment]
Alright, sure, I was busy as hell lately, but I've got some spare time now :)

**Comment by N3ROO** [comment]
Bettercolors 7.4.0 released (for forge): https://github.com/N3ROO/Bettercolors/releases

**Comment by GithubThrowaway69** [comment]
I prefer fabric so I can use new optimization mods such as sodium. No rush though! Take all the time you need.

**Comment by N3ROO** [comment]
The 7.4.0 version for forge was almost ready, that's why it was fast. I just have to port the changes to fabric now. It should be done this week :)
