### ISSUE TITLE
Crash at loading

### ISSUE THREAD

**Issue by FedericoGossi** [N3ROO/Bettercolors#81]
**Describe the bug:**
Crash when loading the mod (version forge 7.4.0) in the Valhelsia 3 modpack 1.16.4
_write here_

**To Reproduce (or what were you doing when it happened):**

_write here_

**Screenshots (if applicable):**

_write here_

**Crash log:**
[crash-2020-12-16_23.40.16-fml.txt](https://github.com/N3ROO/Bettercolors/files/5705873/crash-2020-12-16_23.40.16-fml.txt)

_write here_

- **Have you tried running the mod using the option debug=true**: yes / no
- **Have you tried deleting the config files? (minecraft/config/bc_filename.properties)**: yes / no

**Comment by N3ROO** [comment]
Alright, thanks for your report, I'll fix this issue. I thought that it was fixed, but apparently not

**Comment by N3ROO** [comment]
I fixed the issue, you can download the new version here: https://github.com/N3ROO/Bettercolors/releases/tag/7.4.1-MC1.16.4

If it does not work, try to add "-Djava.awt.headless=false" in the jvm arguments of minecraft:
- Go to the minecraft launcher
- Then, Installations -> Select your config -> edit -> more options -> jvm arguments
