### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by a-a3458** [N3ROO/Bettercolors#84]
**Describe the bug:**

1) I just installed the mod on 1.16.4 and I hit rshift and it doesn't show anything 2) my character is just shifting constantly

**To Reproduce (or what were you doing when it happened):**

all i did was try the mod with forge for 1.16.4 and load up a world and my player is shifting constantly
**Screenshots (if applicable):**

_write here_

**Crash log:**

_write here_

- **Have you tried running the mod using the option debug=true**: yes / no no
- **Have you tried deleting the config files? (minecraft/config/bc_filename.properties)**: yes / no no

**Comment by N3ROO** [comment]
Have you tried clicking on INSERT instead of right shift?
