### ISSUE TITLE
7.4 for forge 1.8.9

### ISSUE THREAD

**Issue by dada513** [N3ROO/Bettercolors#87]
please add the features from 7.4 (right click autoclicker) to a forge 1.8.9 build.

**Comment by N3ROO** [comment]
I'll work on it asap

**Comment by dada513** [comment]
Tysm!

**Comment by N3ROO** [comment]
Done! 1.8.9 mouse events are complicated to deal with, but it is working (and tested)!

https://github.com/N3ROO/Bettercolors/releases/tag/7.4.0-MC1.8.9
