### ISSUE TITLE
1.16.5 fabric support.

### ISSUE THREAD

**Issue by GithubThrowaway69** [N3ROO/Bettercolors#88]
Whenever it conveniences you it would be nice if you could add support for fabric 1.16.5.

**Comment by N3ROO** [comment]
Indeed, it doesn't work for 1.16.5. I'll fix that and release a new version for 1.16.5

**Comment by N3ROO** [comment]
https://github.com/N3ROO/Bettercolors/releases/tag/7.4.0-MC1.16.5fa
